export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const RECEIVE_ALL_OUTAGES = 'RECEIVE_ALL_OUTAGES';
export const RECEIVE_OUTAGE = 'RECEIVE_OUTAGE';
export const UPDATE_OUTAGE = 'UPDATE_OUTAGE';